package project.view.gameview;

public enum Animation {
    SUMMON_MONSTER,
    SET_MONSTER,
    MONSTER_ZONE_TO_GRAVEYARD,
    DRAW_CARD,
    HAND_TO_GRAVEYARD,DIRECT_ATTACK,
    NORMAL_ATTACK ,
    SPELL_TO_GRAVEYARD,SET_SPELL
}
